WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SET DEFINE OFF

CREATE TABLE req_schema_history (
  version VARCHAR2(30 CHAR) PRIMARY KEY,
  checksum VARCHAR2(64 CHAR) NOT NULL,
  applied_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE requirements ADD (
  title VARCHAR2(200 CHAR), original_content CLOB,
  original_source VARCHAR2(20 CHAR) DEFAULT 'UNKNOWN_LEGACY' NOT NULL,
  row_version NUMBER DEFAULT 0 NOT NULL
);
UPDATE requirements SET title=req_key, original_content=content,
  original_source=CASE WHEN version IS NULL THEN 'REGISTERED' ELSE 'UNKNOWN_LEGACY' END;
ALTER TABLE requirements MODIFY (title NOT NULL);

ALTER TABLE requirement_findings ADD (
  analysis_id VARCHAR2(64 CHAR), severity VARCHAR2(20 CHAR) DEFAULT 'ADVISORY' NOT NULL,
  span_start NUMBER, span_end NUMBER, resolution_state VARCHAR2(20 CHAR) DEFAULT 'OPEN' NOT NULL,
  input_hash VARCHAR2(64 CHAR)
);

CREATE TABLE req_working_copies (
  requirement_id NUMBER PRIMARY KEY REFERENCES requirements(id),
  base_version_id NUMBER REFERENCES requirement_versions(id),
  content CLOB NOT NULL, content_hash VARCHAR2(64 CHAR) NOT NULL,
  row_version NUMBER DEFAULT 0 NOT NULL, manual_review_hash VARCHAR2(64 CHAR),
  updated_by NUMBER NOT NULL REFERENCES users(id),
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE work_bundles (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requirement_id NUMBER NOT NULL REFERENCES requirements(id),
  requirement_version_id NUMBER REFERENCES requirement_versions(id),
  revision_no NUMBER NOT NULL, state VARCHAR2(20 CHAR) DEFAULT 'PLANNING' NOT NULL,
  is_current NUMBER(1) DEFAULT 1 NOT NULL, source_status VARCHAR2(20 CHAR) DEFAULT 'VERIFIED' NOT NULL,
  row_version NUMBER DEFAULT 0 NOT NULL, validation_hash VARCHAR2(64 CHAR), manifest_json CLOB,
  created_by NUMBER NOT NULL REFERENCES users(id), created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  confirmed_by NUMBER REFERENCES users(id), confirmed_at TIMESTAMP,
  CONSTRAINT uq_bundle_rev UNIQUE(requirement_id, revision_no),
  CONSTRAINT ck_bundle_current CHECK(is_current IN (0,1)),
  CONSTRAINT ck_bundle_state CHECK(state IN ('PLANNING','ISSUES_READY','GENERATING','REVIEW','CONFIRMED','SUPERSEDED')),
  CONSTRAINT ck_bundle_manifest_json CHECK(manifest_json IS JSON)
);
CREATE UNIQUE INDEX uq_bundle_current ON work_bundles(CASE WHEN is_current=1 THEN requirement_id END);

ALTER TABLE dev_issues ADD (
  bundle_id NUMBER REFERENCES work_bundles(id), symptom CLOB, improvement_req CLOB,
  change_scope CLOB, constraints_note CLOB, before_state CLOB, after_state CLOB,
  due_on DATE, resolved_at TIMESTAMP, fixed_at TIMESTAMP,
  issue_state VARCHAR2(20 CHAR) DEFAULT 'DRAFT' NOT NULL,
  external_key VARCHAR2(100 CHAR), row_version NUMBER DEFAULT 0 NOT NULL
);

ALTER TABLE dev_issue_artifacts ADD (
  schema_version NUMBER DEFAULT 1 NOT NULL,
  generation_state VARCHAR2(20 CHAR) DEFAULT 'READY' NOT NULL,
  row_version NUMBER DEFAULT 0 NOT NULL
);

CREATE TABLE issue_revisions (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  issue_id NUMBER NOT NULL REFERENCES dev_issues(id), revision_no NUMBER NOT NULL,
  snapshot_json CLOB NOT NULL, content_hash VARCHAR2(64 CHAR) NOT NULL,
  reason VARCHAR2(500 CHAR), actor_id NUMBER NOT NULL REFERENCES users(id),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_issue_revision UNIQUE(issue_id,revision_no), CONSTRAINT ck_issue_revision_json CHECK(snapshot_json IS JSON)
);
CREATE TABLE artifact_revisions (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  artifact_id NUMBER NOT NULL REFERENCES dev_issue_artifacts(id), revision_no NUMBER NOT NULL,
  state VARCHAR2(20 CHAR) NOT NULL, content_json CLOB NOT NULL,
  content_hash VARCHAR2(64 CHAR) NOT NULL, reason VARCHAR2(500 CHAR),
  actor_id NUMBER NOT NULL REFERENCES users(id), created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_artifact_revision UNIQUE(artifact_id,revision_no), CONSTRAINT ck_artifact_revision_json CHECK(content_json IS JSON)
);
CREATE TABLE issue_lineage (
  source_issue_id NUMBER NOT NULL REFERENCES dev_issues(id), target_issue_id NUMBER NOT NULL REFERENCES dev_issues(id),
  relation_type VARCHAR2(20 CHAR) NOT NULL, created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  PRIMARY KEY(source_issue_id,target_issue_id,relation_type)
);

CREATE TABLE ai_jobs (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id NUMBER NOT NULL REFERENCES projects(id), requirement_id NUMBER REFERENCES requirements(id),
  bundle_id NUMBER REFERENCES work_bundles(id), kind VARCHAR2(30 CHAR) NOT NULL,
  status VARCHAR2(20 CHAR) DEFAULT 'QUEUED' NOT NULL, idempotency_key VARCHAR2(100 CHAR) NOT NULL,
  request_hash VARCHAR2(64 CHAR) NOT NULL, requested_by NUMBER NOT NULL REFERENCES users(id),
  total_count NUMBER DEFAULT 0 NOT NULL, succeeded_count NUMBER DEFAULT 0 NOT NULL, failed_count NUMBER DEFAULT 0 NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, finished_at TIMESTAMP,
  CONSTRAINT uq_ai_job_key UNIQUE(project_id,idempotency_key)
);
CREATE TABLE ai_tasks (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, job_id NUMBER NOT NULL REFERENCES ai_jobs(id),
  task_key VARCHAR2(160 CHAR) NOT NULL, phase VARCHAR2(30 CHAR) NOT NULL,
  status VARCHAR2(20 CHAR) DEFAULT 'QUEUED' NOT NULL, depends_on_id NUMBER REFERENCES ai_tasks(id),
  attempt NUMBER DEFAULT 0 NOT NULL, max_attempts NUMBER DEFAULT 3 NOT NULL,
  next_run_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, lease_until TIMESTAMP,
  lease_token VARCHAR2(64 CHAR), worker_id VARCHAR2(100 CHAR), input_json CLOB, result_json CLOB,
  error_code VARCHAR2(80 CHAR), error_message VARCHAR2(1000 CHAR),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_ai_task_key UNIQUE(job_id,task_key),
  CONSTRAINT ck_ai_task_input_json CHECK(input_json IS JSON), CONSTRAINT ck_ai_task_result_json CHECK(result_json IS JSON)
);
CREATE INDEX ix_ai_task_claim ON ai_tasks(status,next_run_at,lease_until);

CREATE TABLE review_items (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, bundle_id NUMBER REFERENCES work_bundles(id),
  requirement_id NUMBER NOT NULL REFERENCES requirements(id), finding_id NUMBER REFERENCES requirement_findings(id),
  severity VARCHAR2(20 CHAR) NOT NULL, item_type VARCHAR2(40 CHAR) NOT NULL,
  message VARCHAR2(1000 CHAR) NOT NULL, source_json CLOB, state VARCHAR2(20 CHAR) DEFAULT 'OPEN' NOT NULL,
  fingerprint VARCHAR2(64 CHAR) NOT NULL, created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_review_source_json CHECK(source_json IS JSON)
);
CREATE TABLE user_decisions (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, review_item_id NUMBER NOT NULL REFERENCES review_items(id),
  action VARCHAR2(30 CHAR) NOT NULL, answer CLOB, reason VARCHAR2(1000 CHAR),
  actor_id NUMBER NOT NULL REFERENCES users(id), created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE TABLE req_state_events (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, requirement_id NUMBER NOT NULL REFERENCES requirements(id),
  from_state VARCHAR2(20 CHAR), to_state VARCHAR2(20 CHAR) NOT NULL, reason VARCHAR2(1000 CHAR),
  actor_id NUMBER NOT NULL REFERENCES users(id), created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE TABLE command_receipts (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, project_id NUMBER NOT NULL REFERENCES projects(id),
  command_key VARCHAR2(100 CHAR) NOT NULL, request_hash VARCHAR2(64 CHAR) NOT NULL,
  response_json CLOB NOT NULL, created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_command_receipt UNIQUE(project_id,command_key), CONSTRAINT ck_command_response_json CHECK(response_json IS JSON)
);

CREATE TABLE knowledge_entries (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, project_id NUMBER NOT NULL REFERENCES projects(id),
  source_type VARCHAR2(30 CHAR) NOT NULL, source_id NUMBER NOT NULL, source_version_id NUMBER,
  content CLOB NOT NULL, content_hash VARCHAR2(64 CHAR) NOT NULL, active NUMBER(1) DEFAULT 1 NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX ix_knowledge_project ON knowledge_entries(project_id,active);
CREATE TABLE evidence_links (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, target_type VARCHAR2(30 CHAR) NOT NULL,
  target_id NUMBER NOT NULL, knowledge_entry_id NUMBER NOT NULL REFERENCES knowledge_entries(id),
  quote CLOB NOT NULL, quote_hash VARCHAR2(64 CHAR) NOT NULL, created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE req_attachments (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, requirement_id NUMBER NOT NULL REFERENCES requirements(id),
  file_name VARCHAR2(255 CHAR) NOT NULL, media_type VARCHAR2(100 CHAR) NOT NULL, file_size NUMBER NOT NULL,
  content_blob BLOB NOT NULL, extracted_text CLOB, extraction_state VARCHAR2(20 CHAR) DEFAULT 'QUEUED' NOT NULL,
  uploaded_by NUMBER NOT NULL REFERENCES users(id), created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE TABLE legacy_snapshots (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, source_table VARCHAR2(40 CHAR) NOT NULL,
  source_pk VARCHAR2(100 CHAR) NOT NULL, payload_json CLOB NOT NULL, payload_hash VARCHAR2(64 CHAR) NOT NULL,
  import_state VARCHAR2(20 CHAR) DEFAULT 'SNAPSHOTTED' NOT NULL, error_message VARCHAR2(1000 CHAR),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_legacy_snapshot UNIQUE(source_table,source_pk), CONSTRAINT ck_legacy_payload_json CHECK(payload_json IS JSON)
);
CREATE TABLE legacy_map (
  source_table VARCHAR2(40 CHAR) NOT NULL, source_pk VARCHAR2(100 CHAR) NOT NULL,
  target_type VARCHAR2(30 CHAR) NOT NULL, target_id NUMBER NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  PRIMARY KEY(source_table,source_pk,target_type)
);

INSERT INTO req_schema_history(version,checksum) VALUES ('V002','REQOPS_AGENT_EXPAND_20260925');
COMMIT;
