WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
-- DBA 계정에서 실행한다. 비밀번호는 호출 전에 DEFINE으로 제공하며 파일에 저장하지 않는다.
ALTER SESSION SET "_ORACLE_SCRIPT" = true;
CREATE USER &&REQOPS_DB_USER IDENTIFIED BY "&&REQOPS_DB_PASSWORD";
GRANT CONNECT, RESOURCE TO &&REQOPS_DB_USER;
ALTER USER &&REQOPS_DB_USER QUOTA UNLIMITED ON USERS;
EXIT SUCCESS
