-- ============================================================
--  요구사항 엔지니어링 — Oracle 초기 설정
--  범위: 기능 1 · 회원가입/로그인(USERS) + 프로젝트 관리
--        (PROJECTS · MEMBERSHIPS · PROJECT_TOKENS)
--  실행 순서: (1) DBA(SYSTEM) 계정에서 스키마 생성
--             (2) reqops 계정으로 접속해 테이블 생성
-- ============================================================

-- ── (1) 스키마(사용자) 생성 ──  ※ SYSTEM 등 DBA 계정에서 실행
-- CDB 루트 컨테이너 접속 시 ORA-65096(공통 사용자 이름 부적합) 방지용.
-- 멀티테넌트(12c+) 환경이 아니면 이 줄은 없어도 무방.
ALTER SESSION SET "_ORACLE_SCRIPT" = true;
CREATE USER REQOPS IDENTIFIED BY semes;
GRANT CONNECT, RESOURCE TO REQOPS;
ALTER USER REQOPS QUOTA UNLIMITED ON USERS;

-- ── (2) 테이블 생성 ──  ※ REQOPS 스키마에서 실행 (CONNECT REQOPS/semes)
CREATE TABLE users (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
  emp_no        VARCHAR2(20)   NOT NULL,   -- 사번 (로그인 아이디)
  name          VARCHAR2(50)   NOT NULL,   -- 이름
  dept          VARCHAR2(100),             -- 부서
  password      VARCHAR2(200)  NOT NULL,   -- 비밀번호(평문 문자열)
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_users PRIMARY KEY (id),
  CONSTRAINT uq_users_emp_no UNIQUE (emp_no)
);

COMMENT ON TABLE  users          IS '사용자(로그인 계정)';
COMMENT ON COLUMN users.emp_no   IS '사번 — 로그인 아이디, 고유';
COMMENT ON COLUMN users.password IS '비밀번호(평문 문자열)';

-- ── 프로젝트 관리 (기능 1) ──

CREATE TABLE projects (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
  name          VARCHAR2(100)  NOT NULL,   -- 프로젝트명
  customer      VARCHAR2(100),             -- 고객사
  description   VARCHAR2(500),             -- 설명
  created_by    NUMBER         NOT NULL,   -- 생성자(users.id)
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_projects PRIMARY KEY (id),
  CONSTRAINT fk_projects_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE memberships (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
  user_id       NUMBER         NOT NULL,
  project_id    NUMBER         NOT NULL,
  role          VARCHAR2(20)   NOT NULL,   -- OWNER / MEMBER
  joined_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_memberships PRIMARY KEY (id),
  CONSTRAINT uq_memberships_user_project UNIQUE (user_id, project_id),
  CONSTRAINT fk_memberships_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_memberships_project FOREIGN KEY (project_id) REFERENCES projects(id)
);

CREATE TABLE project_tokens (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
  project_id    NUMBER         NOT NULL,
  token         VARCHAR2(64)   NOT NULL,
  revoked       NUMBER(1) DEFAULT 0 NOT NULL,  -- 0=유효, 1=폐기
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_project_tokens PRIMARY KEY (id),
  CONSTRAINT uq_project_tokens_token UNIQUE (token),
  CONSTRAINT fk_project_tokens_project FOREIGN KEY (project_id) REFERENCES projects(id)
);

COMMENT ON TABLE  projects            IS '프로젝트';
COMMENT ON TABLE  memberships         IS '프로젝트 멤버십(유저-프로젝트-역할)';
COMMENT ON COLUMN memberships.role    IS 'OWNER 또는 MEMBER';
COMMENT ON TABLE  project_tokens      IS '프로젝트 접근 토큰(Open Project용)';
COMMENT ON COLUMN project_tokens.revoked IS '0=유효, 1=폐기(재발급 시 이전 토큰)';

-- ── 요구사항 (기능 2) ──

CREATE TABLE requirements (
  id                NUMBER GENERATED BY DEFAULT AS IDENTITY,
  project_id        NUMBER         NOT NULL,
  req_key           VARCHAR2(50)   NOT NULL,   -- 요구사항 ID (사용자 입력, 프로젝트 내 고유)
  content           CLOB           NOT NULL,   -- 요구사항 내용(등록 원문)
  requester_dept    VARCHAR2(100),             -- 요청자 소속
  requester_name    VARCHAR2(50),              -- 요청자 이름
  state             VARCHAR2(20)   NOT NULL,   -- RECEIVED / IN_REVIEW / PENDING_CONSENSUS / CONFIRMED / REVISING / ON_HOLD
  version           VARCHAR2(20),              -- 확정 시 부여 (예: 1.0.0). 확정 전 NULL
  assignee_id       NUMBER,                    -- 담당자(users.id)
  created_by        NUMBER         NOT NULL,   -- 등록자(users.id)
  created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_requirements PRIMARY KEY (id),
  CONSTRAINT uq_requirements_project_key UNIQUE (project_id, req_key),
  CONSTRAINT fk_requirements_project FOREIGN KEY (project_id) REFERENCES projects(id),
  CONSTRAINT fk_requirements_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);

-- AI 검토 결과. 요구사항 등록 시 AI 서버 응답을 그대로 저장한다(읽기 전용 참고 자료).
CREATE TABLE requirement_findings (
  id                NUMBER GENERATED BY DEFAULT AS IDENTITY,
  requirement_id    NUMBER         NOT NULL,
  finding_type      VARCHAR2(40)   NOT NULL,   -- 정량 기준 부재 / 모호한 정도부사 / ... / 기존 요구사항과 상충
  target_span       VARCHAR2(500),             -- 문제가 된 구절
  reason            VARCHAR2(1000),            -- 왜 문제인지
  suggestion        VARCHAR2(1000),            -- 어떻게 바꾸면 좋은지
  conflict_req_key  VARCHAR2(50),              -- 상충 유형일 때 상대 요구사항 ID
  created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_requirement_findings PRIMARY KEY (id),
  CONSTRAINT fk_findings_requirement FOREIGN KEY (requirement_id) REFERENCES requirements(id)
);

-- AI 제안이 모두 반영된 문장. 확정 화면의 "확정될 본문"에 미리 채워 넣는 값.
CREATE TABLE requirement_ai_drafts (
  id                NUMBER GENERATED BY DEFAULT AS IDENTITY,
  requirement_id    NUMBER         NOT NULL,
  draft_content     CLOB           NOT NULL,
  engine            VARCHAR2(20)   DEFAULT 'rule' NOT NULL,
  created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_requirement_ai_drafts PRIMARY KEY (id),
  CONSTRAINT fk_ai_drafts_requirement FOREIGN KEY (requirement_id) REFERENCES requirements(id)
);

-- 고객 합의 기록. AI 의견이 아무리 합리적이어도 이 기록 없이는 확정할 수 없다.
-- 확정할 때마다 새 행이 쌓이고, 확정 시점에는 가장 마지막 행을 근거로 삼는다.
CREATE TABLE requirement_consensus (
  id                NUMBER GENERATED BY DEFAULT AS IDENTITY,
  requirement_id    NUMBER         NOT NULL,
  method            VARCHAR2(40)   NOT NULL,   -- 대면 미팅 / 유선 / 메일 / 화상회의
  customer_contact  VARCHAR2(100)  NOT NULL,   -- 고객측 담당자 (예: 삼성전자 EDS 김민석 책임)
  agreed_on         DATE           NOT NULL,   -- 합의일
  note              VARCHAR2(2000),            -- 합의 내용 요약
  agreed_content    CLOB           NOT NULL,   -- 이 합의로 확정하기로 한 본문(합의 시점 스냅샷)
  recorded_by       NUMBER         NOT NULL,   -- 기록한 사람(users.id)
  created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_requirement_consensus PRIMARY KEY (id),
  CONSTRAINT fk_consensus_requirement FOREIGN KEY (requirement_id) REFERENCES requirements(id),
  CONSTRAINT fk_consensus_recorded_by FOREIGN KEY (recorded_by) REFERENCES users(id)
);

-- 버전 이력. 확정·재확정마다 커밋처럼 한 줄씩 쌓인다.
CREATE TABLE requirement_versions (
  id                NUMBER GENERATED BY DEFAULT AS IDENTITY,
  requirement_id    NUMBER         NOT NULL,
  version           VARCHAR2(20)   NOT NULL,   -- 1.0.0 / 1.0.1 ...
  title             VARCHAR2(200)  NOT NULL,   -- "최초 확정" 또는 수정 사유
  content           CLOB           NOT NULL,   -- 그 버전으로 확정된 본문
  consensus_id      NUMBER,                    -- 근거가 된 합의 기록
  confirmed_by      NUMBER         NOT NULL,   -- 확정한 사람(users.id)
  created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_requirement_versions PRIMARY KEY (id),
  CONSTRAINT uq_versions_req_version UNIQUE (requirement_id, version),
  CONSTRAINT fk_versions_requirement FOREIGN KEY (requirement_id) REFERENCES requirements(id),
  CONSTRAINT fk_versions_consensus FOREIGN KEY (consensus_id) REFERENCES requirement_consensus(id),
  CONSTRAINT fk_versions_confirmed_by FOREIGN KEY (confirmed_by) REFERENCES users(id)
);

CREATE INDEX ix_requirements_project ON requirements(project_id);
CREATE INDEX ix_findings_requirement ON requirement_findings(requirement_id);
CREATE INDEX ix_consensus_requirement ON requirement_consensus(requirement_id);
CREATE INDEX ix_versions_requirement ON requirement_versions(requirement_id);

COMMENT ON TABLE  requirements                 IS '요구사항';
COMMENT ON COLUMN requirements.req_key         IS '사용자가 입력하는 요구사항 ID — 프로젝트 내 고유';
COMMENT ON COLUMN requirements.content         IS '등록 원문 — 확정 시 확정본으로 갱신';
COMMENT ON COLUMN requirements.state           IS 'RECEIVED/IN_REVIEW/PENDING_CONSENSUS/CONFIRMED/REVISING/ON_HOLD';
COMMENT ON COLUMN requirements.version         IS '확정 시 부여되는 Semver. 확정 전에는 NULL';
COMMENT ON TABLE  requirement_findings         IS 'AI 검토 결과(읽기 전용 참고 자료)';
COMMENT ON TABLE  requirement_ai_drafts        IS 'AI 제안이 반영된 문장 — 확정 화면 본문에 미리 채워짐';
COMMENT ON COLUMN requirement_ai_drafts.engine IS '판정 경로: llm-api(사내 LLM 응답) / rule(규칙 기반만 — LLM 미설정·실패) / unavailable(AI 서버 자체 미응답)';
COMMENT ON TABLE  requirement_consensus        IS '고객 합의 기록 — 이 기록 없이는 확정 불가';
COMMENT ON COLUMN requirement_consensus.agreed_content IS '합의 시점의 본문 스냅샷 — 합의 후 본문이 바뀌면 재합의가 필요한지 판단하는 근거';
COMMENT ON TABLE  requirement_versions         IS '확정·재확정 이력 — 커밋처럼 한 줄씩 쌓인다';
COMMENT ON COLUMN requirement_versions.title   IS '최초 확정이면 "최초 확정", 재확정이면 수정 사유';

-- ============================================================
-- 마이그레이션 — 이미 만들어져 있는 DB에 뒤늦게 추가된 것
-- (새로 설치하는 경우엔 위 CREATE TABLE에 이미 포함되어 있어 아래는 필요 없다)
-- ============================================================

-- requirement_ai_drafts.engine 컬럼이 추가되기 전에 이미 테이블을 만들었다면 실행.
-- ALTER TABLE requirement_ai_drafts ADD engine VARCHAR2(20) DEFAULT 'rule' NOT NULL;

-- 고객 합의·확정 기능을 붙이기 전에 이미 스키마를 만들었다면, 위 CREATE TABLE 중
-- requirement_consensus / requirement_versions 두 개와 그 인덱스만 그대로 실행하면 된다.
-- (기존 테이블은 건드리지 않는다 — 새로 추가되는 테이블뿐이라 데이터 손실 없음)
