-- ============================================================
--  요구사항 엔지니어링 — Oracle 초기 설정
--  범위: 기능 1 · 회원가입/로그인(USERS) + 프로젝트 관리
--        (PROJECTS · MEMBERSHIPS · PROJECT_TOKENS)
--  실행 순서: (1) DBA(SYSTEM) 계정에서 스키마 생성
--             (2) reqops 계정으로 접속해 테이블 생성
-- ============================================================

-- ── (1) 스키마(사용자) 생성 ──  ※ SYSTEM 등 DBA 계정에서 실행
-- CDB 루트 컨테이너 접속 시 ORA-65096(공통 사용자 이름 부적합) 방지용.
-- 멀티테넌트(12c+) 환경이 아니면 이 줄은 없어도 무방.
ALTER SESSION SET "_ORACLE_SCRIPT" = true;
CREATE USER REQOPS IDENTIFIED BY semes;
GRANT CONNECT, RESOURCE TO REQOPS;
ALTER USER REQOPS QUOTA UNLIMITED ON USERS;

-- ── (2) 테이블 생성 ──  ※ REQOPS 스키마에서 실행 (CONNECT REQOPS/semes)
CREATE TABLE users (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
  emp_no        VARCHAR2(20)   NOT NULL,   -- 사번 (로그인 아이디)
  name          VARCHAR2(50)   NOT NULL,   -- 이름
  dept          VARCHAR2(100),             -- 부서
  password      VARCHAR2(200)  NOT NULL,   -- 비밀번호(평문 문자열)
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_users PRIMARY KEY (id),
  CONSTRAINT uq_users_emp_no UNIQUE (emp_no)
);

COMMENT ON TABLE  users          IS '사용자(로그인 계정)';
COMMENT ON COLUMN users.emp_no   IS '사번 — 로그인 아이디, 고유';
COMMENT ON COLUMN users.password IS '비밀번호(평문 문자열)';

-- ── 프로젝트 관리 (기능 1) ──

CREATE TABLE projects (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
  name          VARCHAR2(100)  NOT NULL,   -- 프로젝트명
  customer      VARCHAR2(100),             -- 고객사
  description   VARCHAR2(500),             -- 설명
  created_by    NUMBER         NOT NULL,   -- 생성자(users.id)
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_projects PRIMARY KEY (id),
  CONSTRAINT fk_projects_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE memberships (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
  user_id       NUMBER         NOT NULL,
  project_id    NUMBER         NOT NULL,
  role          VARCHAR2(20)   NOT NULL,   -- OWNER / MEMBER
  joined_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_memberships PRIMARY KEY (id),
  CONSTRAINT uq_memberships_user_project UNIQUE (user_id, project_id),
  CONSTRAINT fk_memberships_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_memberships_project FOREIGN KEY (project_id) REFERENCES projects(id)
);

CREATE TABLE project_tokens (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
  project_id    NUMBER         NOT NULL,
  token         VARCHAR2(64)   NOT NULL,
  revoked       NUMBER(1) DEFAULT 0 NOT NULL,  -- 0=유효, 1=폐기
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_project_tokens PRIMARY KEY (id),
  CONSTRAINT uq_project_tokens_token UNIQUE (token),
  CONSTRAINT fk_project_tokens_project FOREIGN KEY (project_id) REFERENCES projects(id)
);

COMMENT ON TABLE  projects            IS '프로젝트';
COMMENT ON TABLE  memberships         IS '프로젝트 멤버십(유저-프로젝트-역할)';
COMMENT ON COLUMN memberships.role    IS 'OWNER 또는 MEMBER';
COMMENT ON TABLE  project_tokens      IS '프로젝트 접근 토큰(Open Project용)';
COMMENT ON COLUMN project_tokens.revoked IS '0=유효, 1=폐기(재발급 시 이전 토큰)';
