-- ============================================================
--  요구사항 엔지니어링 — Oracle 초기 설정
--  범위: 기능 1 · 회원가입/로그인(USERS) + 프로젝트 관리
--        (PROJECTS · MEMBERSHIPS · PROJECT_TOKENS)
--  실행 순서: (1) DBA(SYSTEM) 계정에서 스키마 생성
--             (2) reqops 계정으로 접속해 테이블 생성
-- ============================================================

-- ── (1) 스키마(사용자) 생성 ──  ※ SYSTEM 등 DBA 계정에서 실행
-- CDB 루트 컨테이너 접속 시 ORA-65096(공통 사용자 이름 부적합) 방지용.
-- 멀티테넌트(12c+) 환경이 아니면 이 줄은 없어도 무방.
ALTER SESSION SET "_ORACLE_SCRIPT" = true;
CREATE USER REQOPS IDENTIFIED BY semes;
GRANT CONNECT, RESOURCE TO REQOPS;
ALTER USER REQOPS QUOTA UNLIMITED ON USERS;

-- ── (2) 테이블 생성 ──  ※ REQOPS 스키마에서 실행 (CONNECT REQOPS/semes)
CREATE TABLE users (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
  emp_no        VARCHAR2(20)   NOT NULL,   -- 사번 (로그인 아이디)
  name          VARCHAR2(50)   NOT NULL,   -- 이름
  dept          VARCHAR2(100),             -- 부서
  password      VARCHAR2(200)  NOT NULL,   -- 비밀번호(평문 문자열)
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_users PRIMARY KEY (id),
  CONSTRAINT uq_users_emp_no UNIQUE (emp_no)
);

COMMENT ON TABLE  users          IS '사용자(로그인 계정)';
COMMENT ON COLUMN users.emp_no   IS '사번 — 로그인 아이디, 고유';
COMMENT ON COLUMN users.password IS '비밀번호(평문 문자열)';

-- ── 프로젝트 관리 (기능 1) ──

CREATE TABLE projects (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
  name          VARCHAR2(100)  NOT NULL,   -- 프로젝트명
  customer      VARCHAR2(100),             -- 고객사
  description   VARCHAR2(500),             -- 설명
  created_by    NUMBER         NOT NULL,   -- 생성자(users.id)
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_projects PRIMARY KEY (id),
  CONSTRAINT fk_projects_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE memberships (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
  user_id       NUMBER         NOT NULL,
  project_id    NUMBER         NOT NULL,
  role          VARCHAR2(20)   NOT NULL,   -- OWNER / MEMBER
  joined_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_memberships PRIMARY KEY (id),
  CONSTRAINT uq_memberships_user_project UNIQUE (user_id, project_id),
  CONSTRAINT fk_memberships_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_memberships_project FOREIGN KEY (project_id) REFERENCES projects(id)
);

CREATE TABLE project_tokens (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
  project_id    NUMBER         NOT NULL,
  token         VARCHAR2(64)   NOT NULL,
  revoked       NUMBER(1) DEFAULT 0 NOT NULL,  -- 0=유효, 1=폐기
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_project_tokens PRIMARY KEY (id),
  CONSTRAINT uq_project_tokens_token UNIQUE (token),
  CONSTRAINT fk_project_tokens_project FOREIGN KEY (project_id) REFERENCES projects(id)
);

COMMENT ON TABLE  projects            IS '프로젝트';
COMMENT ON TABLE  memberships         IS '프로젝트 멤버십(유저-프로젝트-역할)';
COMMENT ON COLUMN memberships.role    IS 'OWNER 또는 MEMBER';
COMMENT ON TABLE  project_tokens      IS '프로젝트 접근 토큰(Open Project용)';
COMMENT ON COLUMN project_tokens.revoked IS '0=유효, 1=폐기(재발급 시 이전 토큰)';

-- ── 요구사항 (기능 2) ──

CREATE TABLE requirements (
  id                NUMBER GENERATED BY DEFAULT AS IDENTITY,
  project_id        NUMBER         NOT NULL,
  req_key           VARCHAR2(50)   NOT NULL,   -- 요구사항 ID (사용자 입력, 프로젝트 내 고유)
  content           CLOB           NOT NULL,   -- 요구사항 내용(등록 원문)
  requester_dept    VARCHAR2(100),             -- 요청자 소속
  requester_name    VARCHAR2(50),              -- 요청자 이름
  state             VARCHAR2(20)   NOT NULL,   -- RECEIVED / IN_REVIEW / PENDING_CONSENSUS / CONFIRMED / REVISING / ON_HOLD
  version           VARCHAR2(20),              -- 확정 시 부여 (예: 1.0.0). 확정 전 NULL
  assignee_id       NUMBER,                    -- 담당자(users.id)
  created_by        NUMBER         NOT NULL,   -- 등록자(users.id)
  created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_requirements PRIMARY KEY (id),
  CONSTRAINT uq_requirements_project_key UNIQUE (project_id, req_key),
  CONSTRAINT fk_requirements_project FOREIGN KEY (project_id) REFERENCES projects(id),
  CONSTRAINT fk_requirements_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);

-- AI 검토 결과. 요구사항 등록 시 AI 서버 응답을 그대로 저장한다(읽기 전용 참고 자료).
CREATE TABLE requirement_findings (
  id                NUMBER GENERATED BY DEFAULT AS IDENTITY,
  requirement_id    NUMBER         NOT NULL,
  finding_type      VARCHAR2(40)   NOT NULL,   -- 정량 기준 부재 / 모호한 정도부사 / ... / 기존 요구사항과 상충
  target_span       VARCHAR2(500),             -- 문제가 된 구절
  reason            VARCHAR2(1000),            -- 왜 문제인지
  suggestion        VARCHAR2(1000),            -- 어떻게 바꾸면 좋은지
  conflict_req_key  VARCHAR2(50),              -- 상충 유형일 때 상대 요구사항 ID
  created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_requirement_findings PRIMARY KEY (id),
  CONSTRAINT fk_findings_requirement FOREIGN KEY (requirement_id) REFERENCES requirements(id)
);

-- AI 제안이 모두 반영된 문장. 확정 화면의 "확정될 본문"에 미리 채워 넣는 값.
CREATE TABLE requirement_ai_drafts (
  id                NUMBER GENERATED BY DEFAULT AS IDENTITY,
  requirement_id    NUMBER         NOT NULL,
  draft_content     CLOB           NOT NULL,
  engine            VARCHAR2(20)   DEFAULT 'rule' NOT NULL,
  created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_requirement_ai_drafts PRIMARY KEY (id),
  CONSTRAINT fk_ai_drafts_requirement FOREIGN KEY (requirement_id) REFERENCES requirements(id)
);

CREATE INDEX ix_requirements_project ON requirements(project_id);
CREATE INDEX ix_findings_requirement ON requirement_findings(requirement_id);

COMMENT ON TABLE  requirements                 IS '요구사항';
COMMENT ON COLUMN requirements.req_key         IS '사용자가 입력하는 요구사항 ID — 프로젝트 내 고유';
COMMENT ON COLUMN requirements.content         IS '등록 원문 — 확정 시 확정본으로 갱신';
COMMENT ON COLUMN requirements.state           IS 'RECEIVED/IN_REVIEW/PENDING_CONSENSUS/CONFIRMED/REVISING/ON_HOLD';
COMMENT ON COLUMN requirements.version         IS '확정 시 부여되는 Semver. 확정 전에는 NULL';
COMMENT ON TABLE  requirement_findings         IS 'AI 검토 결과(읽기 전용 참고 자료)';
COMMENT ON TABLE  requirement_ai_drafts        IS 'AI 제안이 반영된 문장 — 확정 화면 본문에 미리 채워짐';
COMMENT ON COLUMN requirement_ai_drafts.engine IS '판정 경로: llm-api(사내 LLM) / ollama(로컬) / rule(규칙만) / unavailable(AI 미응답)';
