-- Oracle 19c / DBeaver: REQOPS 테이블 전체 초기화
-- 기준: semes 브랜치 bbd8f03, init.sql + V002 + V004 + V005
-- REQOPS로 접속하고 백엔드를 종료한 뒤 이 파일 전체를 스크립트 실행하세요.
-- REQOPS 테이블의 모든 데이터/첨부파일이 영구 삭제됩니다. DDL은 롤백되지 않습니다.
-- REQOPS 계정/비밀번호는 유지됩니다. 다른 스키마의 객체는 변경하지 않습니다.
-- 외부 SQL 파일, SQL*Plus, DBA 접속 없이 실행하는 독립 스크립트입니다.
-- 실제 Oracle에서 실행 검증하지 않았습니다.

DECLARE
  v_external_refs NUMBER;
  PROCEDURE run_ddl(p_sql IN VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  END;
BEGIN
  IF SYS_CONTEXT('USERENV', 'SESSION_USER') <> 'REQOPS'
     OR SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') <> 'REQOPS' THEN
    RAISE_APPLICATION_ERROR(-20001, 'REQOPS 계정/스키마로 접속해야 합니다.');
  END IF;

  -- 보이는 다른 스키마의 외래키가 REQOPS를 참조하면 삭제 전에 중단합니다.
  SELECT COUNT(*) INTO v_external_refs
    FROM all_constraints child
    JOIN all_constraints parent
      ON parent.owner = child.r_owner
     AND parent.constraint_name = child.r_constraint_name
   WHERE child.constraint_type = 'R'
     AND child.owner <> 'REQOPS'
     AND parent.owner = 'REQOPS';
  IF v_external_refs > 0 THEN
    RAISE_APPLICATION_ERROR(-20002, '다른 스키마의 참조가 있어 초기화를 중단합니다.');
  END IF;

  -- REQOPS 내부 외래키만 제거합니다.
  FOR c IN (SELECT table_name, constraint_name FROM user_constraints
             WHERE constraint_type = 'R') LOOP
    EXECUTE IMMEDIATE 'ALTER TABLE REQOPS."' || REPLACE(c.table_name, '"', '""') ||
      '" DROP CONSTRAINT "' || REPLACE(c.constraint_name, '"', '""') || '"';
  END LOOP;

  -- CASCADE CONSTRAINTS를 사용하지 않으므로 다른 스키마의 외래키를 삭제하지 않습니다.
  -- 보이지 않던 외부 참조가 있어도 해당 DROP이 오류로 중단됩니다.
  FOR t IN (SELECT table_name FROM user_tables
             WHERE nested = 'NO' AND secondary = 'N') LOOP
    EXECUTE IMMEDIATE 'DROP TABLE REQOPS."' || REPLACE(t.table_name, '"', '""') || '" PURGE';
  END LOOP;

  -- 현재 프로젝트의 테이블/컬럼/인덱스/제약조건 생성
  run_ddl(q'~CREATE TABLE REQOPS.users (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
  emp_no        VARCHAR2(20)   NOT NULL,   
  name          VARCHAR2(50)   NOT NULL,   
  dept          VARCHAR2(100),             
  password      VARCHAR2(200)  NOT NULL,   
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_users PRIMARY KEY (id),
  CONSTRAINT uq_users_emp_no UNIQUE (emp_no)
)~');

  run_ddl(q'~CREATE TABLE REQOPS.projects (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
  name          VARCHAR2(100)  NOT NULL,   
  customer      VARCHAR2(100),             
  description   VARCHAR2(500),             
  created_by    NUMBER         NOT NULL,   
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_projects PRIMARY KEY (id),
  CONSTRAINT fk_projects_created_by FOREIGN KEY (created_by) REFERENCES REQOPS.users(id)
)~');

  run_ddl(q'~CREATE TABLE REQOPS.memberships (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
  user_id       NUMBER         NOT NULL,
  project_id    NUMBER         NOT NULL,
  role          VARCHAR2(20)   NOT NULL,   
  joined_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_memberships PRIMARY KEY (id),
  CONSTRAINT uq_memberships_user_project UNIQUE (user_id, project_id),
  CONSTRAINT fk_memberships_user FOREIGN KEY (user_id) REFERENCES REQOPS.users(id),
  CONSTRAINT fk_memberships_project FOREIGN KEY (project_id) REFERENCES REQOPS.projects(id)
)~');

  run_ddl(q'~CREATE TABLE REQOPS.project_tokens (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
  project_id    NUMBER         NOT NULL,
  token         VARCHAR2(64)   NOT NULL,
  revoked       NUMBER(1) DEFAULT 0 NOT NULL,  
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_project_tokens PRIMARY KEY (id),
  CONSTRAINT uq_project_tokens_token UNIQUE (token),
  CONSTRAINT fk_project_tokens_project FOREIGN KEY (project_id) REFERENCES REQOPS.projects(id)
)~');

  run_ddl(q'~CREATE TABLE REQOPS.requirements (
  id                NUMBER GENERATED BY DEFAULT AS IDENTITY,
  project_id        NUMBER         NOT NULL,
  req_key           VARCHAR2(50)   NOT NULL,   
  content           CLOB           NOT NULL,   
  requester_dept    VARCHAR2(100),             
  requester_name    VARCHAR2(50),              
  state             VARCHAR2(20)   NOT NULL,   
  version           VARCHAR2(20),              
  assignee_id       NUMBER,                    
  created_by        NUMBER         NOT NULL,   
  created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_requirements PRIMARY KEY (id),
  CONSTRAINT uq_requirements_project_key UNIQUE (project_id, req_key),
  CONSTRAINT fk_requirements_project FOREIGN KEY (project_id) REFERENCES REQOPS.projects(id),
  CONSTRAINT fk_requirements_created_by FOREIGN KEY (created_by) REFERENCES REQOPS.users(id)
)~');

  run_ddl(q'~CREATE TABLE REQOPS.requirement_findings (
  id                NUMBER GENERATED BY DEFAULT AS IDENTITY,
  requirement_id    NUMBER         NOT NULL,
  finding_type      VARCHAR2(40)   NOT NULL,   
  target_span       VARCHAR2(500),             
  reason            VARCHAR2(1000),            
  suggestion        VARCHAR2(1000),            
  conflict_req_key  VARCHAR2(50),              
  created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_requirement_findings PRIMARY KEY (id),
  CONSTRAINT fk_findings_requirement FOREIGN KEY (requirement_id) REFERENCES REQOPS.requirements(id)
)~');

  run_ddl(q'~CREATE TABLE REQOPS.requirement_ai_drafts (
  id                NUMBER GENERATED BY DEFAULT AS IDENTITY,
  requirement_id    NUMBER         NOT NULL,
  draft_content     CLOB           NOT NULL,
  engine            VARCHAR2(20)   DEFAULT 'rule' NOT NULL,
  created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_requirement_ai_drafts PRIMARY KEY (id),
  CONSTRAINT fk_ai_drafts_requirement FOREIGN KEY (requirement_id) REFERENCES REQOPS.requirements(id)
)~');

  run_ddl(q'~CREATE TABLE REQOPS.requirement_consensus (
  id                NUMBER GENERATED BY DEFAULT AS IDENTITY,
  requirement_id    NUMBER         NOT NULL,
  method            VARCHAR2(40)   NOT NULL,   
  customer_contact  VARCHAR2(100)  NOT NULL,   
  agreed_on         DATE           NOT NULL,   
  note              VARCHAR2(2000),            
  agreed_content    CLOB           NOT NULL,   
  recorded_by       NUMBER         NOT NULL,   
  created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_requirement_consensus PRIMARY KEY (id),
  CONSTRAINT fk_consensus_requirement FOREIGN KEY (requirement_id) REFERENCES REQOPS.requirements(id),
  CONSTRAINT fk_consensus_recorded_by FOREIGN KEY (recorded_by) REFERENCES REQOPS.users(id)
)~');

  run_ddl(q'~CREATE TABLE REQOPS.requirement_versions (
  id                NUMBER GENERATED BY DEFAULT AS IDENTITY,
  requirement_id    NUMBER         NOT NULL,
  version           VARCHAR2(20)   NOT NULL,   
  title             VARCHAR2(200)  NOT NULL,   
  content           CLOB           NOT NULL,   
  consensus_id      NUMBER,                    
  confirmed_by      NUMBER         NOT NULL,   
  created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_requirement_versions PRIMARY KEY (id),
  CONSTRAINT uq_versions_req_version UNIQUE (requirement_id, version),
  CONSTRAINT fk_versions_requirement FOREIGN KEY (requirement_id) REFERENCES REQOPS.requirements(id),
  CONSTRAINT fk_versions_consensus FOREIGN KEY (consensus_id) REFERENCES REQOPS.requirement_consensus(id),
  CONSTRAINT fk_versions_confirmed_by FOREIGN KEY (confirmed_by) REFERENCES REQOPS.users(id)
)~');

  run_ddl(q'~CREATE TABLE REQOPS.dev_issues (
  id                NUMBER GENERATED BY DEFAULT AS IDENTITY,
  requirement_id    NUMBER         NOT NULL,
  issue_key         VARCHAR2(60)   NOT NULL,   
  title             VARCHAR2(200)  NOT NULL,
  quote             CLOB,                      
  display_order     NUMBER         NOT NULL,   
  created_by        NUMBER         NOT NULL,   
  created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_dev_issues PRIMARY KEY (id),
  CONSTRAINT uq_dev_issues_req_key UNIQUE (requirement_id, issue_key),
  CONSTRAINT fk_dev_issues_requirement FOREIGN KEY (requirement_id) REFERENCES REQOPS.requirements(id),
  CONSTRAINT fk_dev_issues_created_by FOREIGN KEY (created_by) REFERENCES REQOPS.users(id)
)~');

  run_ddl(q'~CREATE TABLE REQOPS.dev_issue_artifacts (
  id                NUMBER GENERATED BY DEFAULT AS IDENTITY,
  dev_issue_id      NUMBER         NOT NULL,
  artifact_type     VARCHAR2(20)   NOT NULL,   
  state             VARCHAR2(20)   DEFAULT 'DRAFT' NOT NULL,  
  content_json      CLOB           NOT NULL,   
  engine            VARCHAR2(20)   DEFAULT 'rule' NOT NULL,   
  created_by        NUMBER         NOT NULL,
  created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by        NUMBER,
  updated_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_dev_issue_artifacts PRIMARY KEY (id),
  CONSTRAINT uq_dev_issue_artifacts UNIQUE (dev_issue_id, artifact_type),
  CONSTRAINT fk_dev_issue_artifacts_issue FOREIGN KEY (dev_issue_id)
      REFERENCES REQOPS.dev_issues(id) ON DELETE CASCADE,
  CONSTRAINT fk_dev_issue_artifacts_created_by FOREIGN KEY (created_by) REFERENCES REQOPS.users(id)
)~');

  run_ddl(q'~CREATE INDEX REQOPS.ix_requirements_project ON REQOPS.requirements(project_id)~');

  run_ddl(q'~CREATE INDEX REQOPS.ix_findings_requirement ON REQOPS.requirement_findings(requirement_id)~');

  run_ddl(q'~CREATE INDEX REQOPS.ix_consensus_requirement ON REQOPS.requirement_consensus(requirement_id)~');

  run_ddl(q'~CREATE INDEX REQOPS.ix_versions_requirement ON REQOPS.requirement_versions(requirement_id)~');

  run_ddl(q'~CREATE INDEX REQOPS.ix_dev_issues_requirement ON REQOPS.dev_issues(requirement_id)~');

  run_ddl(q'~CREATE INDEX REQOPS.ix_dev_issue_artifacts_issue ON REQOPS.dev_issue_artifacts(dev_issue_id)~');

  run_ddl(q'~CREATE TABLE REQOPS.req_schema_history (
  version VARCHAR2(30 CHAR) PRIMARY KEY,
  checksum VARCHAR2(64 CHAR) NOT NULL,
  applied_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
)~');

  run_ddl(q'~ALTER TABLE REQOPS.requirements ADD (
  title VARCHAR2(200 CHAR), original_content CLOB,
  original_source VARCHAR2(20 CHAR) DEFAULT 'UNKNOWN_LEGACY' NOT NULL,
  row_version NUMBER DEFAULT 0 NOT NULL
)~');

  run_ddl(q'~UPDATE REQOPS.requirements SET title=req_key, original_content=content,
  original_source=CASE WHEN version IS NULL THEN 'REGISTERED' ELSE 'UNKNOWN_LEGACY' END~');

  run_ddl(q'~ALTER TABLE REQOPS.requirements MODIFY (title NOT NULL)~');

  run_ddl(q'~ALTER TABLE REQOPS.requirement_findings ADD (
  analysis_id VARCHAR2(64 CHAR), severity VARCHAR2(20 CHAR) DEFAULT 'ADVISORY' NOT NULL,
  span_start NUMBER, span_end NUMBER, resolution_state VARCHAR2(20 CHAR) DEFAULT 'OPEN' NOT NULL,
  input_hash VARCHAR2(64 CHAR)
)~');

  run_ddl(q'~CREATE TABLE REQOPS.req_working_copies (
  requirement_id NUMBER PRIMARY KEY REFERENCES REQOPS.requirements(id),
  base_version_id NUMBER REFERENCES REQOPS.requirement_versions(id),
  content CLOB NOT NULL, content_hash VARCHAR2(64 CHAR) NOT NULL,
  row_version NUMBER DEFAULT 0 NOT NULL, manual_review_hash VARCHAR2(64 CHAR),
  updated_by NUMBER NOT NULL REFERENCES REQOPS.users(id),
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
)~');

  run_ddl(q'~CREATE TABLE REQOPS.work_bundles (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requirement_id NUMBER NOT NULL REFERENCES REQOPS.requirements(id),
  requirement_version_id NUMBER REFERENCES REQOPS.requirement_versions(id),
  revision_no NUMBER NOT NULL, state VARCHAR2(20 CHAR) DEFAULT 'PLANNING' NOT NULL,
  is_current NUMBER(1) DEFAULT 1 NOT NULL, source_status VARCHAR2(20 CHAR) DEFAULT 'VERIFIED' NOT NULL,
  row_version NUMBER DEFAULT 0 NOT NULL, validation_hash VARCHAR2(64 CHAR), manifest_json CLOB,
  created_by NUMBER NOT NULL REFERENCES REQOPS.users(id), created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  confirmed_by NUMBER REFERENCES REQOPS.users(id), confirmed_at TIMESTAMP,
  CONSTRAINT uq_bundle_rev UNIQUE(requirement_id, revision_no),
  CONSTRAINT ck_bundle_current CHECK(is_current IN (0,1)),
  CONSTRAINT ck_bundle_state CHECK(state IN ('PLANNING','ISSUES_READY','GENERATING','REVIEW','CONFIRMED','SUPERSEDED')),
  CONSTRAINT ck_bundle_manifest_json CHECK(manifest_json IS JSON)
)~');

  run_ddl(q'~CREATE UNIQUE INDEX REQOPS.uq_bundle_current ON REQOPS.work_bundles(CASE WHEN is_current=1 THEN requirement_id END)~');

  run_ddl(q'~ALTER TABLE REQOPS.dev_issues ADD (
  bundle_id NUMBER REFERENCES REQOPS.work_bundles(id), symptom CLOB, improvement_req CLOB,
  change_scope CLOB, constraints_note CLOB, before_state CLOB, after_state CLOB,
  due_on DATE, resolved_at TIMESTAMP, fixed_at TIMESTAMP,
  issue_state VARCHAR2(20 CHAR) DEFAULT 'DRAFT' NOT NULL,
  external_key VARCHAR2(100 CHAR), row_version NUMBER DEFAULT 0 NOT NULL
)~');

  run_ddl(q'~ALTER TABLE REQOPS.dev_issue_artifacts ADD (
  schema_version NUMBER DEFAULT 1 NOT NULL,
  generation_state VARCHAR2(20 CHAR) DEFAULT 'READY' NOT NULL,
  row_version NUMBER DEFAULT 0 NOT NULL
)~');

  run_ddl(q'~CREATE TABLE REQOPS.issue_revisions (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  issue_id NUMBER NOT NULL REFERENCES REQOPS.dev_issues(id), revision_no NUMBER NOT NULL,
  snapshot_json CLOB NOT NULL, content_hash VARCHAR2(64 CHAR) NOT NULL,
  reason VARCHAR2(500 CHAR), actor_id NUMBER NOT NULL REFERENCES REQOPS.users(id),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_issue_revision UNIQUE(issue_id,revision_no), CONSTRAINT ck_issue_revision_json CHECK(snapshot_json IS JSON)
)~');

  run_ddl(q'~CREATE TABLE REQOPS.artifact_revisions (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  artifact_id NUMBER NOT NULL REFERENCES REQOPS.dev_issue_artifacts(id), revision_no NUMBER NOT NULL,
  state VARCHAR2(20 CHAR) NOT NULL, content_json CLOB NOT NULL,
  content_hash VARCHAR2(64 CHAR) NOT NULL, reason VARCHAR2(500 CHAR),
  actor_id NUMBER NOT NULL REFERENCES REQOPS.users(id), created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_artifact_revision UNIQUE(artifact_id,revision_no), CONSTRAINT ck_artifact_revision_json CHECK(content_json IS JSON)
)~');

  run_ddl(q'~CREATE TABLE REQOPS.issue_lineage (
  source_issue_id NUMBER NOT NULL REFERENCES REQOPS.dev_issues(id), target_issue_id NUMBER NOT NULL REFERENCES REQOPS.dev_issues(id),
  relation_type VARCHAR2(20 CHAR) NOT NULL, created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  PRIMARY KEY(source_issue_id,target_issue_id,relation_type)
)~');

  run_ddl(q'~CREATE TABLE REQOPS.ai_jobs (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id NUMBER NOT NULL REFERENCES REQOPS.projects(id), requirement_id NUMBER REFERENCES REQOPS.requirements(id),
  bundle_id NUMBER REFERENCES REQOPS.work_bundles(id), kind VARCHAR2(30 CHAR) NOT NULL,
  status VARCHAR2(20 CHAR) DEFAULT 'QUEUED' NOT NULL, idempotency_key VARCHAR2(100 CHAR) NOT NULL,
  request_hash VARCHAR2(64 CHAR) NOT NULL, requested_by NUMBER NOT NULL REFERENCES REQOPS.users(id),
  total_count NUMBER DEFAULT 0 NOT NULL, succeeded_count NUMBER DEFAULT 0 NOT NULL, failed_count NUMBER DEFAULT 0 NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, finished_at TIMESTAMP,
  CONSTRAINT uq_ai_job_key UNIQUE(project_id,idempotency_key)
)~');

  run_ddl(q'~CREATE TABLE REQOPS.ai_tasks (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, job_id NUMBER NOT NULL REFERENCES REQOPS.ai_jobs(id),
  task_key VARCHAR2(160 CHAR) NOT NULL, phase VARCHAR2(30 CHAR) NOT NULL,
  status VARCHAR2(20 CHAR) DEFAULT 'QUEUED' NOT NULL, depends_on_id NUMBER REFERENCES REQOPS.ai_tasks(id),
  attempt NUMBER DEFAULT 0 NOT NULL, max_attempts NUMBER DEFAULT 3 NOT NULL,
  next_run_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, lease_until TIMESTAMP,
  lease_token VARCHAR2(64 CHAR), worker_id VARCHAR2(100 CHAR), input_json CLOB, result_json CLOB,
  error_code VARCHAR2(80 CHAR), error_message VARCHAR2(1000 CHAR),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_ai_task_key UNIQUE(job_id,task_key),
  CONSTRAINT ck_ai_task_input_json CHECK(input_json IS JSON), CONSTRAINT ck_ai_task_result_json CHECK(result_json IS JSON)
)~');

  run_ddl(q'~CREATE INDEX REQOPS.ix_ai_task_claim ON REQOPS.ai_tasks(status,next_run_at,lease_until)~');

  run_ddl(q'~CREATE TABLE REQOPS.review_items (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, bundle_id NUMBER REFERENCES REQOPS.work_bundles(id),
  requirement_id NUMBER NOT NULL REFERENCES REQOPS.requirements(id), finding_id NUMBER REFERENCES REQOPS.requirement_findings(id),
  severity VARCHAR2(20 CHAR) NOT NULL, item_type VARCHAR2(40 CHAR) NOT NULL,
  message VARCHAR2(1000 CHAR) NOT NULL, source_json CLOB, state VARCHAR2(20 CHAR) DEFAULT 'OPEN' NOT NULL,
  fingerprint VARCHAR2(64 CHAR) NOT NULL, created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_review_source_json CHECK(source_json IS JSON)
)~');

  run_ddl(q'~CREATE TABLE REQOPS.user_decisions (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, review_item_id NUMBER NOT NULL REFERENCES REQOPS.review_items(id),
  action VARCHAR2(30 CHAR) NOT NULL, answer CLOB, reason VARCHAR2(1000 CHAR),
  actor_id NUMBER NOT NULL REFERENCES REQOPS.users(id), created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
)~');

  run_ddl(q'~CREATE TABLE REQOPS.req_state_events (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, requirement_id NUMBER NOT NULL REFERENCES REQOPS.requirements(id),
  from_state VARCHAR2(20 CHAR), to_state VARCHAR2(20 CHAR) NOT NULL, reason VARCHAR2(1000 CHAR),
  actor_id NUMBER NOT NULL REFERENCES REQOPS.users(id), created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
)~');

  run_ddl(q'~CREATE TABLE REQOPS.command_receipts (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, project_id NUMBER NOT NULL REFERENCES REQOPS.projects(id),
  command_key VARCHAR2(100 CHAR) NOT NULL, request_hash VARCHAR2(64 CHAR) NOT NULL,
  response_json CLOB NOT NULL, created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_command_receipt UNIQUE(project_id,command_key), CONSTRAINT ck_command_response_json CHECK(response_json IS JSON)
)~');

  run_ddl(q'~CREATE TABLE REQOPS.knowledge_entries (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, project_id NUMBER NOT NULL REFERENCES REQOPS.projects(id),
  source_type VARCHAR2(30 CHAR) NOT NULL, source_id NUMBER NOT NULL, source_version_id NUMBER,
  content CLOB NOT NULL, content_hash VARCHAR2(64 CHAR) NOT NULL, active NUMBER(1) DEFAULT 1 NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
)~');

  run_ddl(q'~CREATE INDEX REQOPS.ix_knowledge_project ON REQOPS.knowledge_entries(project_id,active)~');

  run_ddl(q'~CREATE TABLE REQOPS.evidence_links (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, target_type VARCHAR2(30 CHAR) NOT NULL,
  target_id NUMBER NOT NULL, knowledge_entry_id NUMBER NOT NULL REFERENCES REQOPS.knowledge_entries(id),
  quote CLOB NOT NULL, quote_hash VARCHAR2(64 CHAR) NOT NULL, created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
)~');

  run_ddl(q'~CREATE TABLE REQOPS.req_attachments (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, requirement_id NUMBER NOT NULL REFERENCES REQOPS.requirements(id),
  file_name VARCHAR2(255 CHAR) NOT NULL, media_type VARCHAR2(100 CHAR) NOT NULL, file_size NUMBER NOT NULL,
  content_blob BLOB NOT NULL, extracted_text CLOB, extraction_state VARCHAR2(20 CHAR) DEFAULT 'QUEUED' NOT NULL,
  uploaded_by NUMBER NOT NULL REFERENCES REQOPS.users(id), created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
)~');

  run_ddl(q'~CREATE TABLE REQOPS.legacy_snapshots (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, source_table VARCHAR2(40 CHAR) NOT NULL,
  source_pk VARCHAR2(100 CHAR) NOT NULL, payload_json CLOB NOT NULL, payload_hash VARCHAR2(64 CHAR) NOT NULL,
  import_state VARCHAR2(20 CHAR) DEFAULT 'SNAPSHOTTED' NOT NULL, error_message VARCHAR2(1000 CHAR),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_legacy_snapshot UNIQUE(source_table,source_pk), CONSTRAINT ck_legacy_payload_json CHECK(payload_json IS JSON)
)~');

  run_ddl(q'~CREATE TABLE REQOPS.legacy_map (
  source_table VARCHAR2(40 CHAR) NOT NULL, source_pk VARCHAR2(100 CHAR) NOT NULL,
  target_type VARCHAR2(30 CHAR) NOT NULL, target_id NUMBER NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  PRIMARY KEY(source_table,source_pk,target_type)
)~');

  run_ddl(q'~INSERT INTO REQOPS.req_schema_history(version,checksum) VALUES ('V002','REQOPS_AGENT_EXPAND_20260925')~');

  run_ddl(q'~ALTER TABLE REQOPS.dev_issue_artifacts DROP CONSTRAINT fk_dev_issue_artifacts_issue~');

  run_ddl(q'~ALTER TABLE REQOPS.dev_issue_artifacts ADD CONSTRAINT fk_dev_issue_artifacts_issue FOREIGN KEY (dev_issue_id) REFERENCES REQOPS.dev_issues(id)~');

  run_ddl(q'~ALTER TABLE REQOPS.dev_issue_artifacts ADD CONSTRAINT ck_artifact_schema CHECK(schema_version IN (1,2))~');

  run_ddl(q'~ALTER TABLE REQOPS.dev_issue_artifacts ADD CONSTRAINT ck_artifact_content_json CHECK(content_json IS JSON)~');

  run_ddl(q'~ALTER TABLE REQOPS.dev_issues ADD CONSTRAINT ck_dev_issue_state CHECK(issue_state IN ('DRAFT','CONFIRMED','RETIRED'))~');

  run_ddl(q'~INSERT INTO REQOPS.req_schema_history(version,checksum) VALUES ('V004','REQOPS_AGENT_CONSTRAINTS_20260925')~');

  run_ddl(q'~CREATE INDEX REQOPS.ix_finding_open_blocker ON REQOPS.requirement_findings(requirement_id, severity, resolution_state)~');

  run_ddl(q'~CREATE INDEX REQOPS.ix_review_item_finding ON REQOPS.review_items(requirement_id, finding_id, state)~');

  run_ddl(q'~CREATE INDEX REQOPS.ix_issue_lineage_target ON REQOPS.issue_lineage(target_issue_id, relation_type)~');

  run_ddl(q'~CREATE UNIQUE INDEX REQOPS.uq_evidence_trace ON REQOPS.evidence_links(target_type, target_id, knowledge_entry_id, quote_hash)~');

  run_ddl(q'~INSERT INTO REQOPS.req_schema_history(version,checksum) VALUES ('V005','REQOPS_REVIEW_TRACE_GUARDS_20260927')~');

  COMMIT;
END;
/

SELECT COUNT(*) AS TABLE_COUNT FROM USER_TABLES;
SELECT VERSION, APPLIED_AT FROM REQOPS.REQ_SCHEMA_HISTORY ORDER BY VERSION;
