'use client';
import {useEffect,useState} from 'react';
import {useParams,useRouter,useSearchParams} from 'next/navigation';
import Link from 'next/link';
import Header from '../../../components/Header';
import ProjectSidebar from '../../../components/ProjectSidebar';
import {getProject,type ProjectDetail} from '../../../lib/api';
import {getCurrentUser} from '../../../lib/session';
import {insight,type Impact,type CodeSnapshot} from '../../../lib/insights';
const labels:Record<string,string>={QUEUED:'분석 대기',RUNNING:'AI 분석 중',RETRY_WAIT:'재시도 대기',READY:'분석 완료',FAILED:'분석 실패',STALE:'최신 내용 재분석 필요'};
export default function InsightsPage(){
 const projectId=Number(useParams<{id:string}>().id);const search=useSearchParams();const router=useRouter();
 const [project,setProject]=useState<ProjectDetail|null>(null);const [rows,setRows]=useState<Impact[]>([]);const [code,setCode]=useState<CodeSnapshot>({});
 const [tab,setTab]=useState(search.get('tab')==='code'?'code':'impact');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [version,setVersion]=useState('');const [files,setFiles]=useState<File[]>([]);const [sidebar,setSidebar]=useState(true);
 async function load(){const u=getCurrentUser();if(!u)return;const [p,r,c]=await Promise.all([getProject(projectId,u.id),insight<Impact[]>(projectId,u.id,'impacts'),insight<CodeSnapshot>(projectId,u.id,'code')]);setProject(p);setRows(r);setCode(c);}
 useEffect(()=>{if(!getCurrentUser()){router.replace('/login');return;}let alive=true;let timer:ReturnType<typeof setTimeout>;async function poll(){try{if(alive)await load();}catch(e){if(alive)setError(e instanceof Error?e.message:'조회 실패');}finally{if(alive)timer=setTimeout(poll,7000);}}poll();return()=>{alive=false;clearTimeout(timer);};},[projectId,router]);
 async function act(id:number,action:string){const u=getCurrentUser();if(!u)return;setBusy(true);setError('');try{await insight(projectId,u.id,`impacts/${id}/${action}`,'POST');await load();}catch(e){setError(e instanceof Error?e.message:'처리 실패');}finally{setBusy(false);}}
 async function upload(){const u=getCurrentUser();if(!u)return;setBusy(true);setError('');try{if(!files.length||files.length>100||files.reduce((n,f)=>n+f.size,0)>2_000_000)throw new Error('소스는 1~100개, 전체 2MB 이하로 선택해 주세요.');const input={version,files:await Promise.all(files.map(async f=>({path:f.webkitRelativePath||f.name,content:await f.text()})))};setCode(await insight<CodeSnapshot>(projectId,u.id,'code','POST',input));setFiles([]);}catch(e){setError(e instanceof Error?e.message:'등록 실패');}finally{setBusy(false);}}
 return <div className="appshell"><Header projectName={project?.name} onToggleSidebar={()=>setSidebar(!sidebar)}/><div className="body">{sidebar&&project&&<ProjectSidebar projectId={projectId} projectName={project.name} active="insights"/>}<main className="main insights-page"><div className="insight-heading"><div><span className="section-kicker">프로젝트 연결</span><h1>변경 영향과 코드 근거</h1><p>어디가 왜 바뀌어야 하는지 확인하세요.</p></div><span className="insight-count">미확인 {rows.filter(r=>!r.read&&r.status==='READY'&&r.decisions?.some(d=>d.judgment!=='NONE')).length}건</span></div>
 <div className="insight-tabs" role="tablist"><button role="tab" aria-selected={tab==='impact'} onClick={()=>setTab('impact')}>변경 영향</button><button role="tab" aria-selected={tab==='code'} onClick={()=>setTab('code')}>코드 근거</button></div>{error&&<p role="alert" className="lmsg err">{error}</p>}
 {tab==='impact'?<div className="impact-list">{rows.length===0&&<section className="insight-card"><h2>새 변경을 기다리고 있어요</h2><p>요구사항을 추가하거나 수정하면 AI가 프로젝트 전체의 영향을 확인합니다.</p></section>}{rows.map(row=><article key={row.id} className="insight-card"><div className="insight-heading"><div><span className="section-kicker">{row.input.proposed?'예상 영향':'확정 변경'} · {row.input.reqKey}</span><h2>{row.summary||'AI가 변경 영향을 확인하고 있어요'}</h2></div><span className={`impact-status ${row.status.toLowerCase()}`}>{labels[row.status]||row.status}</span></div><details className="impact-diff"><summary>변경 전후 보기</summary><div><section><b>변경 전</b><p>{row.input.before||'신규 등록'}</p></section><section><b>변경 후</b><p>{row.input.after}</p></section></div></details>
 {row.status==='FAILED'&&<p className="lmsg err">{row.error||'AI 분석을 완료하지 못했습니다.'}</p>}{row.status==='STALE'&&<p className="lmsg err">요구사항이 변경되어 이전 분석 결과입니다. 최신 내용으로 재분석해 주세요.</p>}
 {row.decisions?.filter(d=>d.judgment!=='NONE').map(d=><section className="impact-target" key={d.reqKey}><div className="insight-heading"><b>{d.reqKey}</b><span>{d.judgment==='UNKNOWN'?'근거 부족':'수정 검토 필요'}</span></div><p className="impact-values">{d.beforeValue||'추가'} <span>→</span> {d.afterValue}</p><blockquote>{d.targetQuote}</blockquote><p><b>영향 이유</b> {d.reason}</p>{d.suggestion&&<p><b>수정 제안</b> {d.suggestion}</p>}<Link href={`/projects/${projectId}/requirements/${row.input.requirements.find(r=>r.reqKey===d.reqKey)?.id}`}>대상 요구사항 열기 →</Link></section>)}
 {row.status==='READY'&&row.decisions?.every(d=>d.judgment==='NONE')&&<p>분석 범위에서 영향받는 요구사항이 없습니다.</p>}{Boolean(row.decisions?.some(d=>d.judgment==='NONE'))&&<details><summary>영향 없음 판정 보기</summary>{row.decisions!.filter(d=>d.judgment==='NONE').map(d=><p key={d.reqKey}><b>{d.reqKey}</b> {d.reason}</p>)}</details>}
 <footer className="insight-actions">{['FAILED','STALE'].includes(row.status)&&<button className="btn" disabled={busy} onClick={()=>act(row.id,'retry')}>재분석</button>}{!row.read&&<button className="btn" disabled={busy} onClick={()=>act(row.id,'read')}>읽음으로 표시</button>}{row.read&&<span>읽음 · 수정 완료와 별도로 관리</span>}</footer></article>)}</div>:<><section className="insight-card"><h2>실제 클래스 소스 등록</h2><p>대상 SW의 소스를 등록하면 실제 클래스와 메서드를 근거로 설계합니다.</p><div className="code-upload"><label>소스 버전<input value={version} onChange={e=>setVersion(e.target.value)} placeholder="예: VCS-v1.2 또는 커밋 ID" disabled={busy}/></label><label>소스 파일<input type="file" multiple accept=".cpp,.cc,.cxx,.h,.hpp,.java,.cs,.py" disabled={busy} onChange={e=>setFiles(Array.from(e.target.files||[]))}/></label><label>폴더 선택<input type="file" multiple {...{webkitdirectory:''}} disabled={busy} onChange={e=>setFiles(Array.from(e.target.files||[]).filter(f=>/\.(cpp|cc|cxx|h|hpp|java|cs|py)$/i.test(f.name)))}/></label></div><p className="note">C++ · Java · C# · Python / 전체 2MB, 최대 100개 파일 · 등록 시 현재 분석 소스 묶음을 교체합니다.</p>{files.length>0&&<p>{files.length}개 선택 · {files.map(f=>f.name).join(', ')}</p>}<button className="btn prim" disabled={busy||!version.trim()||!files.length} onClick={upload}>{busy?'클래스 분석 중…':'소스 등록'}</button></section><section className="insight-card"><div className="insight-heading"><h2>{code.version?`등록 버전 ${code.version}`:'아직 등록된 소스가 없어요'}</h2><span>{code.symbols?.length||0}개 클래스</span></div>{code.warnings?.map((w,i)=><p className="lmsg err" key={i}>{w}</p>)}{code.symbols?.map(s=><details className="coverage-atom" key={s.id}><summary><b>{s.qualifiedName}</b><span>{s.file}:{s.line}</span></summary>{s.methods.map(m=><p key={m.id}><code>{m.signature}</code></p>)}</details>)}<p className="note">소스에서 추출한 호출 표현식을 제공합니다. 동적 호출과 실제 실행 순서는 확인이 필요합니다.</p></section></>}
 </main></div></div>;
}
